### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by altcnews** [FaGuoMa/bitmex-mm-lomond#2]
Hi Dev,

Will keep this clean thats for sure :)
Got this on testnet:

50:50.730|DEBUG |Agent MM | q & prices : bids []
asks [{'price': 5271.5, 't_market': 174.375905, 'q_pos': 0.751}]
50:50.731|DEBUG |Agent MM | cur orders {'bids': [], 'asks':
[{'symbol': 'XBTUSD', 'price': 5271.5, 'orderQty': -1000, 'clOrdID':
'7af83069-62f2-4aee-b65e-3ed58f98e0d6', 'execInst':
'ParticipateDoNotInitiate', 't_market': 174.375905, 'q_pos': 0.751}]}
50:50.731|WARNING |lomond | disconnecting websocket
Traceback (most recent call last):
File "trader.py", line 474, in 
c.run()
File "trader.py", line 434, in run
self.agent.on_l2()
File "/home/ubuntu/xworks/lomond/agent/agent.py", line 466, in on_l2
self.determine_state()
File "/home/ubuntu/xworks/lomond/agent/agent.py", line 185, in
determine_state
self.agent_perform(indi_dict=indi_dict,
curr_inventory=curr_inventory)
File "/home/ubuntu/xworks/lomond/agent/agent.py", line 235, in
agent_perform
bid_post_pxs=bid_post_pxs)
File "/home/ubuntu/xworks/lomond/agent/agent.py", line 323, in
evaluate_outstanding_orders
bb = sorted(cur_orders['bids'], key= flt_fun, reverse=True)[0]
IndexError: list index out of range

As per previous suggestion from you, i already maximised the max inventory.

Please advice.
Thanks & Regards.

**Comment by FaGuoMa** [comment]
Hi, this is a bug happening when orders are one-sided. I have put a fix that **should** work so feel free to test it. Frankly, I'm happy to help when I can but am fairly busy these days

**Comment by altcnews** [comment]
Hi Dev,

It's good to see you back....just take your time, i still trying to use this and will report for any results.
I'm on test net and using your latest fix updated for XBTUSD and bit make the skew (bid/ask) = 15

it's fine until got this:
33:43.245|DEBUG   |Agent MM  |   indi_dict {'current_ob': {'bid':
[5008.5, 5008.0], 'ask': [5009.5, 5010.0]}, 'order_stats': <bound
method OrderKeep.exec_report of <orders.OrderKeep object at
0x7fd90d40ae10>>, 'trade_ratio': None, 'init_margin_bal': 8490800,
'cur_margin_bal': 8490800, 'max_loss_bal': 5943560.0}
33:43.245|DEBUG   |Agent MM  |  in agent perform with state: None
33:43.246|CRITICAL|Agent MM  |  Skew weird state - Quoting Wide
33:43.246|DEBUG   |Agent MM  |  bids: [5001.0, 5000.5] 
asks: [5017.0, 5017.5]
33:43.246|DEBUG   |Agent MM  |  q & prices : bids [{'price': 5001.0,
't_market': 37.892238, 'q_pos': 0.935}] 
asks []
33:43.246|DEBUG   |Agent MM  |  cur orders {'bids': [{'symbol':
'XBTUSD', 'price': 5001.0, 'orderQty': 15, 'clOrdID': 'da1a92af-b0ee-
44ce-8a58-009221f2e6ba', 'execInst': 'ParticipateDoNotInitiate',
't_market': 37.892238, 'q_pos': 0.935}], 'asks': []}
33:43.246|DEBUG   |Agent MM  |  ba {'symbol': 'XBTUSD', 'price':
5001.0, 'orderQty': 15, 'clOrdID': 'da1a92af-b0ee-44ce-8a58-
009221f2e6ba', 'execInst': 'ParticipateDoNotInitiate', 't_market':
37.892238, 'q_pos': 0.935} | bb None
33:43.246|WARNING |lomond    |  disconnecting websocket
Traceback (most recent call last):
 File "trader.py", line 474, in <module>
   c.run()
 File "trader.py", line 434, in run
   self.agent.on_l2()
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 473, in on_l2
   self.determine_state()
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 185, in
determine_state
   self.agent_perform(indi_dict=indi_dict,
curr_inventory=curr_inventory)
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 235, in
agent_perform
   bid_post_pxs=bid_post_pxs)
 File "/home/ubuntu/xworks/lomond/agent/agent.py", line 336, in
evaluate_outstanding_orders
   self.debug("ba price {} | bbo {} | equal
{}".format(ba['price'],red(self.bbo(lvl=5)['ask'][0]), ba['price'] ==
red(self.bbo(lvl=5)['ask'][0])))
TypeError: 'NoneType' object is not subscriptable

ps:
this is still happened at default conf, without changing the skew.

Appreciate for your hard work.
Thanks & Regards.

**Comment by FaGuoMa** [comment]
hum, hard to know why. The debugger crash because (probably) it doesn't have the boo right. I have wrapped the logger line with exception catcher, it would be interesting to see what the `self.bbo` status is then

Two things, though:

1. this is a separate issue, so it probably would have warranted opening a new ticket. This is important if anyone else has issues
2. I assume you don't code, but if you do **do feel free to issue PRs**. If you don't, do know that as much as I am willing to help **I will not be maintaining what is really an exploration project alone**

**Comment by altcnews** [comment]
Hi,
No problem dev, i will try to find out in my spare time also.
I don't code, i will be a regular tester for this and report the result :)

Thanks & Regards.

**Comment by FaGuoMa** [comment]
OK, @altcnews happy to help if I can
Closing the issue for housekeeping
