### ISSUE TITLE
http 401 unauthorized

### ISSUE THREAD

**Issue by nateflanders** [FaGuoMa/bitmex-mm-lomond#4]
After setting configs and other instructions, receiving the following: 

`python3 trader.py
23:43.250|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
23:43.251|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
23:43.251|WARNING |devmm     |  backing off for 6.960200879753413 s
23:50.767|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
23:50.767|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
23:50.767|WARNING |devmm     |  backing off for 5.528794874741516 s
23:56.876|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
23:56.876|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
23:56.876|WARNING |devmm     |  backing off for 5.345986775378155 s
24:02.784|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
24:02.784|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
24:02.785|WARNING |devmm     |  backing off for 6.905008154012075 s
24:10.247|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
24:10.248|WARNING |devmm     |  <response HTTP/1.1 401 Unauthorized>
24:10.248|WARNING |devmm     |  backing off for 5.035879645614055 s

`

Any thoughts? @FaGuoMa

**Comment by FaGuoMa** [comment]
This feels like you're using a testnet key on mainnet or vice-versa. Closing because this is a bitmex message
